#!/bin/bash

echo "====DOCKER-AS-VM===="

PATH_DEPO=$(pwd)/

echo "Current path: $PATH_DEPO"

case "$1" in
start)
	scripts/create_docker $PATH_DEPO $2
	;;
stop)
	scripts/kill_docker $PATH_DEPO $2
	;;
configure)
	scripts/configure_server
	;;
*)
	echo "Usage: $0 {start <name>|stop <name>|configure}"
esac

exit 0
