#!/bin/bash

echo "====DOCKER-AS-VM===="

PATH_DEPO=$(pwd)/

echo "Current path: $PATH_DEPO"

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root" 
	exit 1
fi

case "$1" in
start)
	scripts/create_docker $PATH_DEPO $2
	;;
stop)
	scripts/kill_docker $PATH_DEPO $2
	;;
configure)
	scripts/configure_server
	;;
*)
	echo "Usage: $0 {start <name>|stop <name>|configure}"
esac

exit 0
