#!/bin/bash

#Constants
VIRTUALHOST_TEMPLATE_FILE=virtualhost-apache-template.conf
APACHE_SITES=/etc/apache2/sites-available/

echo "---- Creating docker"

if [ $(id -u) -ne 0 ]; then
	echo "- not root"
fi

if [ $# -lt 1 ]
then
	echo "ERROR: not enough arguments"
	exit 1
fi

echo "- docker name: $1"

DOCKER_RUNNING_FILE=docker$1.running

#Kill old running docker
./kill_docker $1
#if [ -f $DOCKER_RUNNING_FILE ]; then
#	OLD_NAME=$(cat $DOCKER_RUNNING_FILE)
#
#	if [ "$(docker ps -q -f name=$OLD_NAME)" ]; then
#		echo "- found existing docker"
#
#		RUNNING=$(docker inspect --format="{{.State.Running}}" $OLD_NAME 2> /dev/null)
#
#		if [ ! "$RUNNING" == "false" ]; then
#			docker kill $OLD_NAME
#		fi
#
#		docker rm $OLD_NAME
#	fi
#fi

#Generate new name with timestamp
date=$(date +"%s")
name=$1$date

echo $name > $DOCKER_RUNNING_FILE

echo "---- Setting virtualhosts"

PORT=$(( ( $RANDOM % 3000 )  + 62000 ))
PORTS_DOCKER=""
PORTS_STRING=""

while read port_number service_name
do
	echo "- service $service_name at port $port_number"

	SERVER_NAME="$1-$service_name.dyser.tech"
	VIRTUALHOST_FILENAME="virtualhost-$1-$port_number.conf"

	cp $VIRTUALHOST_TEMPLATE_FILE $VIRTUALHOST_FILENAME 

	sed -i "s/SERVER_NAME/$SERVER_NAME/g" $VIRTUALHOST_FILENAME
	sed -i "s/PORT/$PORT/g" $VIRTUALHOST_FILENAME

	if [ -f $APACHE_SITES$VIRTUAHOST_FILENAME ]; then
		echo "- already exists virtualhost"
 		rm $APACHE_SITES$VIRTUALHOST_FILENAME
	fi

	mv $VIRTUALHOST_FILENAME $APACHE_SITES

	a2ensite $VIRTUALHOST_FILENAME > /dev/null
	
	PORTS_DOCKER="$PORTS_DOCKER $port_number"
	PORTS_STRING="$PORTS_STRING -p $PORT:$port_number"
	PORT=$(( $PORT + 1))
done < PORTS

service apache2 restart

#Setting dockerfile
sed "s/PORTS/$PORTS_DOCKER/g" Dockerfile_template > Dockerfile

#Run docker

echo "---- Running docker"

#docker build -t sshdo .
#docker run -d -p $2:22 --name $name -t sshdo

echo "docker run -d $PORTS_STRING --name $name -t sshdo"

#docker exec $name -t docker-entrypoint.sh
