#!/bin/bash

if [ $(id -u) -ne 0 ]; then
	echo "- not root"
	exit 1
fi

if [ $# -lt 2 ]; then
	echo "- missing docker <name>"
	exit 1
fi

echo "---- Setting constants"

#Constants
PATH_DEPO=$1

DOCKER_NAME=$2
DOCKER_UNAME=${DOCKER_NAME}$(date +"%s")

SCRIPTS_DIR=${PATH_DEPO}scripts/
CONFIG_DIR=${PATH_DEPO}config/
TEMPLATES_DIR=${PATH_DEPO}templates/
INSTANCE_DIR=${PATH_DEPO}instance-${DOCKER_NAME}/

VIRTUALHOST_TEMPLATE_FILE=${TEMPLATES_DIR}virtualhost-apache-template.conf
APACHE_SITES=/etc/apache2/sites-available/

DOCKER_FILE_TEMPLATE=${TEMPLATES_DIR}Dockerfile_template
DOCKER_FILE_FINAL=${INSTANCE_DIR}Dockerfile

DOCKER_RUNNING_FILE=${INSTANCE_DIR}docker.running
PORTS_FILE=${CONFIG_DIR}ports

COMMANDS_CONFIG_FILE=${CONFIG_DIR}docker-commands.sh
COMMANDS_INSTANCE_FILE=${INSTANCE_DIR}docker-entrypoint.sh

echo "---- Creating docker"
echo "- docker name ${DOCKER_NAME}"

mkdir -p $INSTANCE_DIR

#Kill old running docker
${SCRIPTS_DIR}kill_docker ${PATH_DEPO} ${DOCKER_NAME}

#Generate new name with timestamp
#date=$(date +"%s")
#name=${DOCKER_NAME}${date}

echo $DOCKER_UNAME > ${DOCKER_RUNNING_FILE}

echo "---- Setting virtualhosts"

PORT=$(( ( $RANDOM % 3000 )  + 62000 ))
PORTS_DOCKER=""
PORTS_STRING=""

while read port_number service_name
do
	echo "- service $service_name at port $port_number"

	SERVER_NAME="$DOCKER_NAME-$service_name.dyser.tech"

	VIRTUALHOST_FILENAME=virtualhost-${DOCKER_NAME}-${port_number}.conf
	VIRTUALHOST_FILE=${INSTANCE_DIR}${VIRTUALHOST_FILENAME}

	rm -f ${VIRTUALHOST_FILE}
	cp $VIRTUALHOST_TEMPLATE_FILE ${VIRTUALHOST_FILE} 

	sed -i "s/SERVER_NAME/$SERVER_NAME/g" $VIRTUALHOST_FILE
	sed -i "s/PORT/$PORT/g" $VIRTUALHOST_FILE

	if [ -f ${APACHE_SITES}${VIRTUAHOST_FILENAME} ]; then
		echo "- already exists virtualhost"
 		rm ${APACHE_SITES}${VIRTUALHOST_FILENAME}
	fi

	cp ${VIRTUALHOST_FILE} $APACHE_SITES

	a2ensite $VIRTUALHOST_FILENAME > /dev/null
	
	PORTS_DOCKER="$PORTS_DOCKER $port_number"
	PORTS_STRING="$PORTS_STRING -p $PORT:$port_number"
	PORT=$(( $PORT + 1))
done < $PORTS_FILE

service apache2 restart

#Setting docker
sed "s/PORTS/$PORTS_DOCKER/g" $DOCKER_FILE_TEMPLATE  > $DOCKER_FILE_FINAL

cp $COMMANDS_CONFIG_FILE $COMMANDS_INSTANCE_FILE

#Run docker

echo "---- Running docker"

docker build -t sshdo .
docker run -d $PORTS_STRING --name $DOCKER_UNAME -t sshdo

docker exec $DOCKER_UNAME -t $COMMANDS_INSTANCE_FILE
